In [14]:
import numpy as np
import pandas as pd
import matplotlib
import matplotlib.pyplot as plt
import os

In [15]:
import librosa
import librosa.display

In [16]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [17]:
df = pd.read_csv('/content/drive/MyDrive/balanced_train_segments.csv',sep=', ')
df = df.drop(['start_seconds', 'end_seconds'], axis=1)
df = df.rename(columns={'"YTID': 'YTID', 'positive_labels"': 'labels'})

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  """Entry point for launching an IPython kernel.

In [18]:
df.head()

           YTID                           labels
0  "--PJHxphWEs         ""/m/09x0r,/t/dd00088"""
1  "--ZhevVpy1s                   ""/m/012xff"""
2  "--aE2O5G5WE  ""/m/03fwl,/m/04rlf,/m/09x0r"""
3  "--aO5cdqSAg       ""/t/dd00003,/t/dd00005"""
4  "--aaILOrkII         ""/m/032s66,/m/073cg4"""

In [19]:
def Convert(string):
    l = string.split(",")
    return l

temp = pd.DataFrame()

for i in df['YTID']:
  df['YTID'] = df['YTID'].replace([i],i.replace('"', ''))

x = df.YTID

for i in df['labels']:
  new_string = i.replace('"', '')
  l = Convert(new_string)
  temp = temp.append({'label': i,  'labels': l}, ignore_index=True)
  temp['YTID'] = x
  df = temp.drop(['label'], axis=1)

In [20]:
df.head()

                           labels         YTID
0          [/m/09x0r, /t/dd00088]  --PJHxphWEs
1                     [/m/012xff]  --ZhevVpy1s
2  [/m/03fwl, /m/04rlf, /m/09x0r]  --aE2O5G5WE
3        [/t/dd00003, /t/dd00005]  --aO5cdqSAg
4          [/m/032s66, /m/073cg4]  --aaILOrkII

In [21]:
df2 = pd.read_csv("/content/drive/MyDrive/class_labels_indices.csv")
df2 = df2.drop(['index'], axis=1)
df2.head()

         mid                   display_name
0   /m/09x0r                         Speech
1  /m/05zppz      Male speech, man speaking
2   /m/02zsn  Female speech, woman speaking
3   /m/0ytgt     Child speech, kid speaking
4  /m/01h8n0                   Conversation

In [22]:
all_keywords_list  = []
for i in range(len(df['labels'])):
  keywords = ""
  for j in df['labels'][i]:
    for k in range(len(df2['mid'])):
      if j == df2['mid'][k]:
        keywords += df2['display_name'][k] + ";"
  keywords = keywords[:-1]
  all_keywords_list.append(keywords)

In [23]:
df['Keywords'] = all_keywords_list
df = df.drop(['labels'], axis=1)
df

              YTID                                           Keywords
0      --PJHxphWEs                                        Speech;Gush
1      --ZhevVpy1s                                         Toothbrush
2      --aE2O5G5WE                                  Goat;Music;Speech
3      --aO5cdqSAg                         Male singing;Child singing
4      --aaILOrkII                           Gunshot, gunfire;Cap gun
...            ...                                                ...
22155  zyqg4pYEioQ                              Speech;Sewing machine
22156  zz0ddNfz0h0  Motor vehicle (road);Ice cream truck, ice crea...
22157  zz8TGV83nkE     Motor vehicle (road);Engine;Motorcycle;Vehicle
22158  zzlK8KDqlr0  Computer keyboard;Clicking;Speech;Inside, smal...
22159  zzya4dDVRLk                               Sine wave;Chirp tone

[22160 rows x 2 columns]

In [26]:
df.to_csv ("YouTubeID_and_Keywords.csv", index=False, header=True)